In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [55]:
import pandas as pd
import numpy as np

DATA_PATH = '/content/drive/MyDrive/데이콘 캐글 컴페티션/DACON_23.07_PowerConsumption/'
SEED = 42

In [56]:
import matplotlib.pyplot as plt

In [57]:
train_df = pd.read_csv(f"{DATA_PATH}train.csv")
test_df = pd.read_csv(f"{DATA_PATH}test.csv")
building_info = pd.read_csv(f"{DATA_PATH}building_info.csv")

In [58]:
train_df

,num_date_time,건물번호,일시,기온(C),강수량(mm),풍속(m/s),습도(%),일조(hr),일사(MJ/m2),전력소비량(kWh)
0,1_20220601 00,1,20220601 00,18.6,NaN,0.9,42.0,NaN,NaN,1085.28
1,1_20220601 01,1,20220601 01,18.0,NaN,1.1,45.0,NaN,NaN,1047.36
2,1_20220601 02,1,20220601 02,17.7,NaN,1.5,45.0,NaN,NaN,974.88
3,1_20220601 03,1,20220601 03,16.7,NaN,1.4,48.0,NaN,NaN,953.76
4,1_20220601 04,1,20220601 04,18.4,NaN,2.8,43.0,NaN,NaN,986.40
...,...,...,...,...,...,...,...,...,...,...
203995,100_20220824 19,100,20220824 19,23.1,NaN,0.9,86.0,0.5,NaN,881.04
203996,100_20220824 20,100,20220824 20,22.4,NaN,1.3,86.0,0.0,NaN,798.96
203997,100_20220824 21,100,20220824 21,21.3,NaN,1.0,92.0,NaN,NaN,825.12
203998,100_20220824 22,100,20220824 22,21.0,NaN,0.3,94.0,NaN,NaN,640.08
203999,100_20220824 23,100,20220824 23,20.7,NaN,0.1,95.0,NaN,NaN,540.24

In [59]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204000 entries, 0 to 203999
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   num_date_time  204000 non-null  object
 1   건물번호           204000 non-null  int64
 2   일시             204000 non-null  object
 3   기온(C)          204000 non-null  float64
 4   강수량(mm)        43931 non-null   float64
 5   풍속(m/s)        203981 non-null  float64
 6   습도(%)          203991 non-null  float64
 7   일조(hr)         128818 non-null  float64
 8   일사(MJ/m2)      116087 non-null  float64
 9   전력소비량(kWh)     204000 non-null  float64
dtypes: float64(7), int64(1), object(2)
memory usage: 15.6+ MB

In [60]:
test_df

         num_date_time  건물번호           일시  기온(C)  강수량(mm)  풍속(m/s)  습도(%)
0        1_20220825 00     1  20220825 00   23.5      0.0      2.2     72
1        1_20220825 01     1  20220825 01   23.0      0.0      0.9     72
2        1_20220825 02     1  20220825 02   22.7      0.0      1.5     75
3        1_20220825 03     1  20220825 03   22.1      0.0      1.3     78
4        1_20220825 04     1  20220825 04   21.8      0.0      1.0     77
...                ...   ...          ...    ...      ...      ...    ...
16795  100_20220831 19   100  20220831 19   22.5      0.0      0.9     84
16796  100_20220831 20   100  20220831 20   20.7      0.0      0.4     95
16797  100_20220831 21   100  20220831 21   20.2      0.0      0.4     98
16798  100_20220831 22   100  20220831 22   20.1      0.0      1.1     97
16799  100_20220831 23   100  20220831 23   19.1      0.0      0.1     99

[16800 rows x 7 columns]

In [61]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16800 entries, 0 to 16799
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   num_date_time  16800 non-null  object
 1   건물번호           16800 non-null  int64
 2   일시             16800 non-null  object
 3   기온(C)          16800 non-null  float64
 4   강수량(mm)        16800 non-null  float64
 5   풍속(m/s)        16800 non-null  float64
 6   습도(%)          16800 non-null  int64
dtypes: float64(3), int64(2), object(2)
memory usage: 918.9+ KB

In [62]:
building_info

    건물번호    건물유형    연면적(m2)   냉방면적(m2) 태양광용량(kW) ESS저장용량(kWh) PCS용량(kW)
0      1    건물기타  110634.00   39570.00         -            -         -
1      2    건물기타  122233.47   99000.00         -            -         -
2      3    건물기타  171243.00  113950.00        40            -         -
3      4    건물기타   74312.98   34419.62        60            -         -
4      5    건물기타  205884.00  150000.00         -         2557      1000
..   ...     ...        ...        ...       ...          ...       ...
95    96  호텔및리조트   93314.00   60500.00         -            -         -
96    97  호텔및리조트   55144.67   25880.00         -            -         -
97    98  호텔및리조트   53578.62   17373.75         -            -         -
98    99  호텔및리조트   53499.00   40636.00         -            -         -
99   100  호텔및리조트   57497.84   40035.23         -            -         -

[100 rows x 7 columns]

In [63]:
building_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   건물번호          100 non-null    int64
 1   건물유형          100 non-null    object
 2   연면적(m2)       100 non-null    float64
 3   냉방면적(m2)      100 non-null    float64
 4   태양광용량(kW)     100 non-null    object
 5   ESS저장용량(kWh)  100 non-null    object
 6   PCS용량(kW)     100 non-null    object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.6+ KB

In [64]:
building_info['태양광용량(kW)'] = building_info['태양광용량(kW)'].replace('-', 0).astype(float)
building_info['ESS저장용량(kWh)'] = building_info['ESS저장용량(kWh)'].replace('-', 0).astype(float)
building_info['PCS용량(kW)'] = building_info['PCS용량(kW)'].replace('-', 0).astype(float)

In [65]:
building_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   건물번호          100 non-null    int64
 1   건물유형          100 non-null    object
 2   연면적(m2)       100 non-null    float64
 3   냉방면적(m2)      100 non-null    float64
 4   태양광용량(kW)     100 non-null    float64
 5   ESS저장용량(kWh)  100 non-null    float64
 6   PCS용량(kW)     100 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 5.6+ KB

In [66]:
train_df = pd.merge(train_df, building_info, on='건물번호', how='left')
test_df = pd.merge(test_df, building_info, on='건물번호', how='left')

In [67]:
# num_date_time, 태양광, ESS, PCS 제거
train_df = train_df.drop(columns=['num_date_time', '태양광용량(kW)','ESS저장용량(kWh)', 'PCS용량(kW)'])
test_df = test_df.drop(columns=['num_date_time', '태양광용량(kW)', 'ESS저장용량(kWh)', 'PCS용량(kW)'])

In [68]:
# 변수 영문명으로 변경
train_cols = ['building_num', 'date_time', 'temp', 'pred', 'wind', 'hum', 'sunshine', 'solar_rad', 'power', 'type', 'area', 'cooling_area']
test_cols = ['building_num', 'date_time', 'temp', 'pred', 'wind', 'hum', 'type', 'area', 'cooling_area']

train_df.columns = train_cols
test_df.columns = test_cols

# 전력량 맨 앞으로 이동
train_df = train_df[['power','building_num', 'date_time', 'temp', 'pred', 'wind', 'hum', 'sunshine', 'solar_rad', 'type', 'area', 'cooling_area']]

In [69]:
train_df.head()

,power,building_num,date_time,temp,pred,wind,hum,sunshine,solar_rad,type,area,cooling_area
0,1085.28,1,20220601 00,18.6,NaN,0.9,42.0,NaN,NaN,건물기타,110634.0,39570.0
1,1047.36,1,20220601 01,18.0,NaN,1.1,45.0,NaN,NaN,건물기타,110634.0,39570.0
2,974.88,1,20220601 02,17.7,NaN,1.5,45.0,NaN,NaN,건물기타,110634.0,39570.0
3,953.76,1,20220601 03,16.7,NaN,1.4,48.0,NaN,NaN,건물기타,110634.0,39570.0
4,986.40,1,20220601 04,18.4,NaN,2.8,43.0,NaN,NaN,건물기타,110634.0,39570.0

In [70]:
test_df.head()

,building_num,date_time,temp,pred,wind,hum,type,area,cooling_area
0,1,20220825 00,23.5,0.0,2.2,72,건물기타,110634.0,39570.0
1,1,20220825 01,23.0,0.0,0.9,72,건물기타,110634.0,39570.0
2,1,20220825 02,22.7,0.0,1.5,75,건물기타,110634.0,39570.0
3,1,20220825 03,22.1,0.0,1.3,78,건물기타,110634.0,39570.0
4,1,20220825 04,21.8,0.0,1.0,77,건물기타,110634.0,39570.0

In [71]:
# 면적 제거
train_df = train_df.drop(columns=['area', 'cooling_area'])
test_df = test_df.drop(columns=['area', 'cooling_area'])

In [72]:
# 강수랑, 일조, 일사, 풍속 결측치 0.0으로 채우기
train_df['pred'] = train_df['pred'].fillna(0.0)
train_df['sunshine'] = train_df['sunshine'].fillna(0.0)
train_df['solar_rad'] = train_df['solar_rad'].fillna(0.0)
train_df['wind'] = train_df['wind'].fillna(0.0)

In [73]:
# 결측치 처리
mask = train_df['building_num'] == 9
train_df.loc[mask, 'hum'] = train_df['hum'][mask].interpolate()

mask = train_df['building_num'] == 15
train_df.loc[mask, 'hum'] = train_df['hum'][mask].interpolate()

mask = train_df['building_num'] == 87
train_df.loc[mask, 'hum'] = train_df['hum'][mask].interpolate()

mask = train_df['building_num'] == 90
train_df.loc[mask, 'hum'] = train_df['hum'][mask].interpolate()

mask = train_df['building_num'] == 100
train_df.loc[mask, 'hum'] = train_df['hum'][mask].interpolate()

- 노이즈 제거 검토

In [74]:
check_df = train_df[['date_time', 'power']]
check_df

          date_time    power
0       20220601 00  1085.28
1       20220601 01  1047.36
2       20220601 02   974.88
3       20220601 03   953.76
4       20220601 04   986.40
...             ...      ...
203995  20220824 19   881.04
203996  20220824 20   798.96
203997  20220824 21   825.12
203998  20220824 22   640.08
203999  20220824 23   540.24

[204000 rows x 2 columns]

In [75]:
#시계열 특성을 학습에 반영하기 위해 일시를 월, 일, 시간으로 나눕니다
date = pd.to_datetime(train_df['date_time'])
train_df['time'] = date.dt.hour
train_df['day'] = date.dt.weekday
train_df['month'] = date.dt.month
train_df['week'] = date.dt.isocalendar().week
train_df['day_of_year'] = date.dt.dayofyear

In [76]:
date = pd.to_datetime(test_df['date_time'])
test_df['time'] = date.dt.hour
test_df['day'] = date.dt.weekday
test_df['month'] = date.dt.month
test_df['week'] = date.dt.isocalendar().week
test_df['day_of_year'] = date.dt.dayofyear

In [77]:
train_df['week'] = train_df['week'].astype(int)
test_df['week'] = test_df['week'].astype(int)

In [78]:
train_df['sin_time'] = np.sin(2*np.pi*train_df['time']/24)
train_df['cos_time'] = np.cos(2*np.pi*train_df['time']/24)

test_df['sin_time'] = np.sin(2*np.pi*test_df['time']/24)
test_df['cos_time'] = np.cos(2*np.pi*test_df['time']/24)

In [79]:
train_df.shape , test_df.shape

((204000, 17), (16800, 14))

- 노이즈 제거
    - rolling_avg 적용

In [80]:
train_RM = train_df[['date_time', 'building_num', 'temp', 'wind', 'hum']] # 'pred'는 실제값 사용
test_RM = test_df[['date_time', 'building_num', 'temp', 'wind', 'hum']] # 'pred'는 실제값 사용

In [81]:
rolling_mean_df = pd.concat([train_RM,test_RM], axis=0).reset_index(drop=True)
rolling_mean_df.shape , rolling_mean_df.isnull().sum().sum()

((220800, 5), 0)

In [82]:
# 이동평균 12시간
window_size = 12
rolling_mean_df['temp_RM'] = rolling_mean_df.groupby('building_num')['temp'].rolling(window=window_size).mean().reset_index(level=0, drop=True)
# rolling_mean_df['pred_RM'] = rolling_mean_df.groupby('building_num')['pred'].rolling(window=window_size).mean().reset_index(level=0, drop=True)
rolling_mean_df['wind_RM'] = rolling_mean_df.groupby('building_num')['wind'].rolling(window=window_size).mean().reset_index(level=0, drop=True)
rolling_mean_df['hum_RM'] = rolling_mean_df.groupby('building_num')['hum'].rolling(window=window_size).mean().reset_index(level=0, drop=True)
rolling_mean_df

,date_time,building_num,temp,wind,hum,temp_RM,wind_RM,hum_RM
0,20220601 00,1,18.6,0.9,42.0,NaN,NaN,NaN
1,20220601 01,1,18.0,1.1,45.0,NaN,NaN,NaN
2,20220601 02,1,17.7,1.5,45.0,NaN,NaN,NaN
3,20220601 03,1,16.7,1.4,48.0,NaN,NaN,NaN
4,20220601 04,1,18.4,2.8,43.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
220795,20220831 19,100,22.5,0.9,84.0,23.125000,1.050000,81.250000
220796,20220831 20,100,20.7,0.4,95.0,23.133333,1.058333,81.000000
220797,20220831 21,100,20.2,0.4,98.0,23.058333,1.025000,81.250000
220798,20220831 22,100,20.1,1.1,97.0,22.933333,0.991667,81.916667
220799,20220831 23,100,19.1,0.1,99.0,22.650000,0.875000,83.250000

In [83]:
# 지수이동평균 12시간
window_size = 12
rolling_mean_df['temp_EMA'] = rolling_mean_df.groupby('building_num')['temp'].transform(lambda x: x.ewm(span=window_size, adjust=False).mean())
# rolling_mean_df['pred_EMA'] = rolling_mean_df.groupby('building_num')['pred'].transform(lambda x: x.ewm(span=window_size, adjust=False).mean())
rolling_mean_df['wind_EMA'] = rolling_mean_df.groupby('building_num')['wind'].transform(lambda x: x.ewm(span=window_size, adjust=False).mean())
rolling_mean_df['hum_EMA'] = rolling_mean_df.groupby('building_num')['hum'].transform(lambda x: x.ewm(span=window_size, adjust=False).mean())
rolling_mean_df

,date_time,building_num,temp,wind,hum,temp_RM,wind_RM,hum_RM,temp_EMA,wind_EMA,hum_EMA
0,20220601 00,1,18.6,0.9,42.0,NaN,NaN,NaN,18.600000,0.900000,42.000000
1,20220601 01,1,18.0,1.1,45.0,NaN,NaN,NaN,18.507692,0.930769,42.461538
2,20220601 02,1,17.7,1.5,45.0,NaN,NaN,NaN,18.383432,1.018343,42.852071
3,20220601 03,1,16.7,1.4,48.0,NaN,NaN,NaN,18.124442,1.077060,43.644060
4,20220601 04,1,18.4,2.8,43.0,NaN,NaN,NaN,18.166836,1.342127,43.544974
...,...,...,...,...,...,...,...,...,...,...,...
220795,20220831 19,100,22.5,0.9,84.0,23.125000,1.050000,81.250000,23.017679,0.998363,81.625374
220796,20220831 20,100,20.7,0.4,95.0,23.133333,1.058333,81.000000,22.661113,0.906307,83.683009
220797,20220831 21,100,20.2,0.4,98.0,23.058333,1.025000,81.250000,22.282480,0.828414,85.885623
220798,20220831 22,100,20.1,1.1,97.0,22.933333,0.991667,81.916667,21.946714,0.870196,87.595527
220799,20220831 23,100,19.1,0.1,99.0,22.650000,0.875000,83.250000,21.508758,0.751705,89.350061

In [84]:
rolling_mean_df.head(14)

,date_time,building_num,temp,wind,hum,temp_RM,wind_RM,hum_RM,temp_EMA,wind_EMA,hum_EMA
0,20220601 00,1,18.6,0.9,42.0,NaN,NaN,NaN,18.600000,0.900000,42.000000
1,20220601 01,1,18.0,1.1,45.0,NaN,NaN,NaN,18.507692,0.930769,42.461538
2,20220601 02,1,17.7,1.5,45.0,NaN,NaN,NaN,18.383432,1.018343,42.852071
3,20220601 03,1,16.7,1.4,48.0,NaN,NaN,NaN,18.124442,1.077060,43.644060
4,20220601 04,1,18.4,2.8,43.0,NaN,NaN,NaN,18.166836,1.342127,43.544974
5,20220601 05,1,17.2,2.1,46.0,NaN,NaN,NaN,18.018092,1.458723,43.922670
6,20220601 06,1,16.3,1.0,50.0,NaN,NaN,NaN,17.753770,1.388150,44.857644
7,20220601 07,1,17.4,1.3,50.0,NaN,NaN,NaN,17.699344,1.374589,45.648776
8,20220601 08,1,20.6,1.8,44.0,NaN,NaN,NaN,18.145599,1.440037,45.395118
9,20220601 09,1,23.2,1.7,41.0,NaN,NaN,NaN,18.923199,1.480031,44.718946
10,20220601 10,1,24.8,2.5,35.0,NaN,NaN,NaN,19.827322,1.636949,43.223723
11,20220601 11,1,26.3,2.7,31.0,19.600000,1.733333,43.333333,20.823119,1.800496,41.343151
12,20220601 12,1,27.5,3.4,23.0,20.341667,1.941667,41.750000,21.850331,2.046573,38.521127
13,20220601 13,1,28.3,4.2,22.0,21.200000,2.200000,39.833333,22.842588,2.377870,35.979416

In [85]:
rolling_mean_df[:204001]

,date_time,building_num,temp,wind,hum,temp_RM,wind_RM,hum_RM,temp_EMA,wind_EMA,hum_EMA
0,20220601 00,1,18.6,0.9,42.0,NaN,NaN,NaN,18.600000,0.900000,42.000000
1,20220601 01,1,18.0,1.1,45.0,NaN,NaN,NaN,18.507692,0.930769,42.461538
2,20220601 02,1,17.7,1.5,45.0,NaN,NaN,NaN,18.383432,1.018343,42.852071
3,20220601 03,1,16.7,1.4,48.0,NaN,NaN,NaN,18.124442,1.077060,43.644060
4,20220601 04,1,18.4,2.8,43.0,NaN,NaN,NaN,18.166836,1.342127,43.544974
...,...,...,...,...,...,...,...,...,...,...,...
203996,20220824 20,100,22.4,1.3,86.0,24.316667,1.316667,79.166667,23.985044,1.301026,80.886507
203997,20220824 21,100,21.3,1.0,92.0,24.141667,1.308333,79.583333,23.571960,1.254714,82.596275
203998,20220824 22,100,21.0,0.3,94.0,23.908333,1.216667,80.333333,23.176274,1.107835,84.350694
203999,20220824 23,100,20.7,0.1,95.0,23.658333,1.150000,81.000000,22.795309,0.952783,85.989049
204000,20220825 00,1,23.5,2.2,72.0,25.600000,2.108333,65.333333,24.896022,2.161533,67.049625

In [86]:
rolling_mean_df[-16801:]

,date_time,building_num,temp,wind,hum,temp_RM,wind_RM,hum_RM,temp_EMA,wind_EMA,hum_EMA
203999,20220824 23,100,20.7,0.1,95.0,23.658333,1.150000,81.000000,22.795309,0.952783,85.989049
204000,20220825 00,1,23.5,2.2,72.0,25.600000,2.108333,65.333333,24.896022,2.161533,67.049625
204001,20220825 01,1,23.0,0.9,72.0,25.216667,1.941667,66.250000,24.604326,1.967451,67.811221
204002,20220825 02,1,22.7,1.5,75.0,24.850000,1.950000,67.333333,24.311353,1.895535,68.917187
204003,20220825 03,1,22.1,1.3,78.0,24.475000,1.891667,68.416667,23.971145,1.803915,70.314543
...,...,...,...,...,...,...,...,...,...,...,...
220795,20220831 19,100,22.5,0.9,84.0,23.125000,1.050000,81.250000,23.017679,0.998363,81.625374
220796,20220831 20,100,20.7,0.4,95.0,23.133333,1.058333,81.000000,22.661113,0.906307,83.683009
220797,20220831 21,100,20.2,0.4,98.0,23.058333,1.025000,81.250000,22.282480,0.828414,85.885623
220798,20220831 22,100,20.1,1.1,97.0,22.933333,0.991667,81.916667,21.946714,0.870196,87.595527
220799,20220831 23,100,19.1,0.1,99.0,22.650000,0.875000,83.250000,21.508758,0.751705,89.350061

In [87]:
cols = ['temp_RM','wind_RM','hum_RM','temp_EMA','wind_EMA','hum_EMA'] # 'pred_RM', 'pred_EMA'

# train_ft에 concat
train_add = rolling_mean_df[:204000][cols]
train_df = pd.concat([train_df,train_add],axis=1)

# test_ft에 concat
test_add = rolling_mean_df[-16800:][cols].reset_index(drop=True)
test_df = pd.concat([test_df,test_add],axis=1)

train_df.shape , test_df.shape # 전력량, 일조량, 일사량

((204000, 23), (16800, 20))

In [88]:
train_df['day_of_year'].unique()

array([152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203,
       204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216,
       217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229,
       230, 231, 232, 233, 234, 235, 236])

In [89]:
# 6월 1일 삭제 --> day_of_year == 152
mask_train = train_df['day_of_year'] != 152
train_df = train_df[mask_train].reset_index(drop=True)
train_df.shape

(201600, 23)

In [90]:
train_df['THI'] = 1.8*train_df['temp_RM'] - 0.55*(1-train_df['hum_RM']/100)*(1.8*train_df['temp_RM']-26)+32
test_df['THI'] = 1.8*test_df['temp_RM'] - 0.55*(1 - test_df['hum_RM']/100)*(1.8*test_df['temp_RM'] - 26)+32

In [91]:
# 체감온도 변수 추가
def wet_temp(temp, hum):
    tw = temp*np.arctan(0.151977*(hum + 8.313659)*0.5) + np.arctan(temp + hum) - np.arctan(hum - 1.67633) + 0.00391838*1.5*np.arctan(0.023101*hum) - 4.686035
    return tw

def feels_temp(temp, hum):
    tw = wet_temp(temp, hum)
    ft = -0.2442 + 0.55399*tw + 0.45535*temp - 0.0022*(tw**2) + 0.00278*tw*temp + 3.0
    return ft

In [92]:
train_df['feels_temp'] = feels_temp(train_df['temp_RM'], train_df['hum_RM'])
test_df['feels_temp'] = feels_temp(test_df['temp_RM'], test_df['hum_RM'])

In [93]:
# cdh(cooling degree hour) 변수 추가
def CDH(xs):
    ys = []
    for i in range(len(xs)):
        if i < 11:
            ys.append(np.sum(xs[:(i+1)]-26))
        else:
            ys.append(np.sum(xs[(i-11):(i+1)]-26))
    return np.array(ys)

In [94]:
cdhs = np.array([])
for num in range(1,101,1):
    temp = train_df[train_df['building_num'] == num]
    cdh = CDH(temp['temp_RM'].values)
    cdhs = np.concatenate([cdhs, cdh])
train_df['CDH'] = cdhs

cdhs = np.array([])
for num in range(1,101,1):
    temp = test_df[test_df['building_num'] == num]
    cdh = CDH(temp['temp_RM'].values)
    cdhs = np.concatenate([cdhs, cdh])
test_df['CDH'] = cdhs

In [95]:
# 시간별 전력량 평균 추가
power_hour_mean = train_df.groupby(['building_num', 'time'])['power'].mean().reset_index()
train_df['hour_mean'] = train_df.apply(lambda x :power_hour_mean.loc[(power_hour_mean.building_num == x['building_num']) & (power_hour_mean.time == x['time']), 'power'].values[0], axis=1)
test_df['hour_mean'] = test_df.apply(lambda x :power_hour_mean.loc[(power_hour_mean.building_num == x['building_num']) & (power_hour_mean.time == x['time']), 'power'].values[0], axis=1)

In [96]:
# 요일별 시간별 전력량 평균 추가
power_mean = pd.pivot_table(train_df, values = 'power', index = ['building_num', 'time', 'day'], aggfunc = np.mean).reset_index()

train_df['day_hour_mean'] = train_df.apply(lambda x : power_mean.loc[(power_mean.building_num == x['building_num']) & (power_mean.time == x['time']) & (power_mean.day == x['day']) ,'power'].values[0], axis = 1)
test_df['day_hour_mean'] = test_df.apply(lambda x : power_mean.loc[(power_mean.building_num == x['building_num']) & (power_mean.time == x['time']) & (power_mean.day == x['day']) ,'power'].values[0], axis = 1)

In [97]:
# 시간별 전력량 표준편차 추가
power_hour_std = pd.pivot_table(train_df, values = 'power', index = ['building_num', 'time'], aggfunc = np.std).reset_index()

train_df['hour_std'] = train_df.apply(lambda x : power_hour_std.loc[(power_hour_std.building_num == x['building_num']) & (power_hour_std.time == x['time']) ,'power'].values[0], axis = 1)
test_df['hour_std'] = test_df.apply(lambda x : power_hour_std.loc[(power_hour_std.building_num == x['building_num']) & (power_hour_std.time == x['time']) ,'power'].values[0], axis = 1)

In [98]:
# 열지수 단계별로 구분
T = train_df['temp_RM']*9/5 + 32 # 화씨로 전환
RH = train_df['hum_RM']
train_df['heat_index'] = -42.379 + 2.04901523*T + 10.14333127*RH - .22475541*T*RH - .00683783*T*T - .05481717*RH*RH + .00122874*T*T*RH + .00085282*T*RH*RH - .00000199*T*T*RH*RH
train_df['heat_index'] = (train_df['heat_index']-32) * 5/9 # 섭씨로 전환
train_df.loc[train_df['heat_index']<32, 'heat_index'] = 0
train_df.loc[(train_df['heat_index']>=32) & (train_df['heat_index']<41), 'heat_index'] = 1
train_df.loc[(train_df['heat_index']>=41) & (train_df['heat_index']<54), 'heat_index'] = 2
train_df.loc[(train_df['heat_index']>=54) & (train_df['heat_index']<66), 'heat_index'] = 3
train_df.loc[train_df['heat_index']>=66, 'heat_index'] = 4

T = test_df['temp_RM']*9/5 + 32 # 화씨로 전환
RH = test_df['hum_RM']
test_df['heat_index'] = -42.379 + 2.04901523*T + 10.14333127*RH - .22475541*T*RH - .00683783*T*T - .05481717*RH*RH + .00122874*T*T*RH + .00085282*T*RH*RH - .00000199*T*T*RH*RH
test_df['heat_index'] = (test_df['heat_index']-32) * 5/9 # 섭씨로 전환
test_df.loc[test_df['heat_index']<32, 'heat_index'] = 0
test_df.loc[(test_df['heat_index']>=32) & (test_df['heat_index']<41), 'heat_index'] = 1
test_df.loc[(test_df['heat_index']>=41) & (test_df['heat_index']<54), 'heat_index'] = 2
test_df.loc[(test_df['heat_index']>=54) & (test_df['heat_index']<66), 'heat_index'] = 3
test_df.loc[test_df['heat_index']>=66, 'heat_index'] = 4

In [99]:
# 폭염 여부 추가
train_df['heat_wave'] = 0
train_df.loc[train_df['temp_RM'] >= 33, 'heat_wave'] = 1

test_df['heat_wave'] = 0
test_df.loc[test_df['temp_RM'] >= 33, 'heat_wave'] = 1

- 기온의 제곱

In [100]:
train_df['temp_2'] = train_df['temp']**2
test_df['temp_2'] = test_df['temp']**2

- 7일전 대비 전력 변화량의 평균 (168일)

In [101]:
train_df['power_change_rate_7d'] = (train_df['power'] - train_df.groupby('building_num')['power'].shift(7*24)) / train_df.groupby('building_num')['power'].shift(7*24)

train_df['day_within_cycle'] = train_df.index % (7*24)

avg_power_change_rate_7d = train_df.groupby(['building_num','day_within_cycle' ])['power_change_rate_7d'].mean().reset_index()
avg_power_change_rate_7d.rename(columns={'power_change_rate_7d': 'avg_power_change_rate_7d'}, inplace=True)

train_df = train_df.merge(avg_power_change_rate_7d, on=['building_num','day_within_cycle'], how='left')
cols = ['day_within_cycle','power_change_rate_7d']
train_df = train_df.drop(columns = cols)

train_df['avg_power_change_rate_7d'].nunique()

last_rows = train_df.groupby('building_num').tail(168)['avg_power_change_rate_7d'].reset_index().drop('index',axis=1)
test_df = pd.concat([test_df, last_rows], axis=1)

- 1일전 대비 전력 변화량의 평균 (24시간)

In [102]:
train_df['power_change_rate_24h'] = (train_df['power'] - train_df.groupby('building_num')['power'].shift(24)) / train_df.groupby('building_num')['power'].shift(24)

train_df['day_within_cycle'] = train_df.index % (24)

avg_power_change_rate_24h = train_df.groupby(['building_num','day_within_cycle' ])['power_change_rate_24h'].mean().reset_index()
avg_power_change_rate_24h.rename(columns={'power_change_rate_24h': 'avg_power_change_rate_24h'}, inplace=True)

train_df = train_df.merge(avg_power_change_rate_24h, on=['building_num','day_within_cycle'], how='left')
cols = ['day_within_cycle','power_change_rate_24h']
train_df = train_df.drop(columns = cols)

last_rows = train_df.groupby('building_num').tail(168)['avg_power_change_rate_24h'].reset_index().drop('index',axis=1)
test_df = pd.concat([test_df, last_rows], axis=1)

In [103]:
train_df

,power,building_num,date_time,temp,pred,wind,hum,sunshine,solar_rad,type,...,feels_temp,CDH,hour_mean,day_hour_mean,hour_std,heat_index,heat_wave,temp_2,avg_power_change_rate_7d,avg_power_change_rate_24h
0,1034.40,1,20220602 00,18.1,0.0,0.4,67.0,0.0,0.0,건물기타,...,28.818026,-1.850000,1713.711429,1627.80,444.306331,0.0,0,327.61,0.069171,0.021710
1,973.92,1,20220602 01,17.6,0.0,0.8,69.0,0.0,0.0,건물기타,...,27.987268,-4.591667,1629.468571,1550.08,437.718795,0.0,0,309.76,0.072765,0.023154
2,909.12,1,20220602 02,17.2,0.0,0.7,71.0,0.0,0.0,건물기타,...,27.080175,-8.266667,1513.305714,1431.12,410.362488,0.0,0,295.84,0.071155,0.025346
3,893.28,1,20220602 03,17.2,0.0,2.2,75.0,0.0,0.0,건물기타,...,26.152269,-12.866667,1443.122857,1372.20,389.916262,0.0,0,295.84,0.067707,0.030905
4,924.00,1,20220602 04,17.2,0.0,2.0,81.0,0.0,0.0,건물기타,...,25.248724,-18.333333,1452.808571,1381.72,379.995696,0.0,0,295.84,0.063264,0.033128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201595,881.04,100,20220824 19,23.1,0.0,0.9,86.0,0.5,0.0,호텔및리조트,...,30.510262,-35.641667,1012.602857,976.06,161.150392,0.0,0,533.61,0.039282,0.004240
201596,798.96,100,20220824 20,22.4,0.0,1.3,86.0,0.0,0.0,호텔및리조트,...,30.441848,-33.391667,930.205714,892.92,137.040302,0.0,0,501.76,0.040570,0.004927
201597,825.12,100,20220824 21,21.3,0.0,1.0,92.0,0.0,0.0,호텔및리조트,...,30.233938,-31.266667,831.714286,786.62,128.125250,0.0,0,453.69,0.053521,0.006987
201598,640.08,100,20220824 22,21.0,0.0,0.3,94.0,0.0,0.0,호텔및리조트,...,29.960151,-29.483333,724.480000,667.94,112.413470,0.0,0,441.00,0.036985,0.008615
201599,540.24,100,20220824 23,20.7,0.0,0.1,95.0,0.0,0.0,호텔및리조트,...,29.663653,-28.083333,589.820000,566.94,91.531822,0.0,0,428.49,0.047592,0.007734

In [104]:

train_df.isnull().sum(), test_df.isnull().sum()

(power                         0
 building_num                  0
 date_time                     0
 temp                          0
 pred                          0
 wind                          0
 hum                           0
 sunshine                      0
 solar_rad                     0
 type                          0
 time                          0
 day                           0
 month                         0
 week                          0
 day_of_year                   0
 sin_time                      0
 cos_time                      0
 temp_RM                       0
 wind_RM                       0
 hum_RM                        0
 temp_EMA                      0
 wind_EMA                      0
 hum_EMA                       0
 THI                           0
 feels_temp                    0
 CDH                           0
 hour_mean                     0
 day_hour_mean                 0
 hour_std                      0
 heat_index                    0
 heat_wave                     0
 temp_2                        0
 avg_power_change_rate_7d     12
 avg_power_change_rate_24h    84
 dtype: int64,
 building_num                 0
 date_time                    0
 temp                         0
 pred                         0
 wind                         0
 hum                          0
 type                         0
 time                         0
 day                          0
 month                        0
 week                         0
 day_of_year                  0
 sin_time                     0
 cos_time                     0
 temp_RM                      0
 wind_RM                      0
 hum_RM                       0
 temp_EMA                     0
 wind_EMA                     0
 hum_EMA                      0
 THI                          0
 feels_temp                   0
 CDH                          0
 hour_mean                    0
 day_hour_mean                0
 hour_std                     0
 heat_index                   0
 heat_wave                    0
 temp_2                       0
 avg_power_change_rate_7d     1
 avg_power_change_rate_24h    7
 dtype: int64)

In [105]:

train_df = train_df.interpolate()
test_df = test_df.interpolate()

train_df.isnull().sum(), test_df.isnull().sum()

(power                        0
 building_num                 0
 date_time                    0
 temp                         0
 pred                         0
 wind                         0
 hum                          0
 sunshine                     0
 solar_rad                    0
 type                         0
 time                         0
 day                          0
 month                        0
 week                         0
 day_of_year                  0
 sin_time                     0
 cos_time                     0
 temp_RM                      0
 wind_RM                      0
 hum_RM                       0
 temp_EMA                     0
 wind_EMA                     0
 hum_EMA                      0
 THI                          0
 feels_temp                   0
 CDH                          0
 hour_mean                    0
 day_hour_mean                0
 hour_std                     0
 heat_index                   0
 heat_wave                    0
 temp_2                       0
 avg_power_change_rate_7d     0
 avg_power_change_rate_24h    0
 dtype: int64,
 building_num                 0
 date_time                    0
 temp                         0
 pred                         0
 wind                         0
 hum                          0
 type                         0
 time                         0
 day                          0
 month                        0
 week                         0
 day_of_year                  0
 sin_time                     0
 cos_time                     0
 temp_RM                      0
 wind_RM                      0
 hum_RM                       0
 temp_EMA                     0
 wind_EMA                     0
 hum_EMA                      0
 THI                          0
 feels_temp                   0
 CDH                          0
 hour_mean                    0
 day_hour_mean                0
 hour_std                     0
 heat_index                   0
 heat_wave                    0
 temp_2                       0
 avg_power_change_rate_7d     0
 avg_power_change_rate_24h    0
 dtype: int64)

In [107]:
train_df.shape, test_df.shape

((201600, 34), (16800, 31))

In [108]:
train_df.to_csv(f'{DATA_PATH}train_features_ys_rm.csv', index=False)
test_df.to_csv(f'{DATA_PATH}test_features_ys_rm.csv', index=False)